"""Builds a distributable LiveTranslator, then strips what it does not use.

Two things make the difference between a ~1.1GB build and a ~270MB one:

  * ENGINE = "lean" drives Argos's CTranslate2 models directly, so
    argostranslate -> stanza -> torch (526MB) never enters the bundle.
  * PyInstaller's speech_recognition hook collects a PocketSphinx offline
    model and FLAC binaries for Linux and macOS. None of it is reachable
    on Windows with the engines this app uses, so it is pruned afterwards.
"""

import os
import pathlib
import shutil
import subprocess
import sys

ROOT = pathlib.Path(__file__).resolve().parent
DIST = ROOT / "dist" / "LiveTranslator"
STAGE = ROOT / "build" / "argos_bundle"

# Shipped inside the exe so a fresh machine can translate immediately. The
# speech model is not bundled - faster-whisper fetches it once on first run,
# which keeps this build ~148MB smaller.
BUNDLE_PAIRS = [("en", "zt"), ("zt", "en")]

EXCLUDES = [
    # the whole reason the build is small
    "torch", "torchvision", "torchaudio", "stanza", "spacy", "thinc", "blis",
    "argostranslate", "sympy", "networkx",
    # never imported by the app
    "matplotlib", "scipy", "pandas", "PIL", "googletrans", "deepl",
    "transformers", "pytest", "IPython", "notebook",
]

# Reachable only through recognisers this app never calls
PRUNE_GLOBS = [
    "speech_recognition/pocketsphinx-data/**/*",
    "speech_recognition/flac-linux-*",
    "speech_recognition/flac-mac",
    "**/*.pdb",
]


def folder_size(path):
    return sum(f.stat().st_size for f in path.rglob("*") if f.is_file())


def stage_packs():
    """Copy the translation packs we ship, minus what the lean engine ignores.

    Each Argos pack carries a stanza/ folder for sentence splitting. The lean
    engine splits on punctuation instead, so that folder is dead weight.
    """
    import json

    src_root = (pathlib.Path.home() / ".local" / "share"
                / "argos-translate" / "packages")
    shutil.rmtree(STAGE, ignore_errors=True)
    STAGE.mkdir(parents=True, exist_ok=True)

    available = {}
    for pkg in src_root.iterdir() if src_root.exists() else []:
        meta = pkg / "metadata.json"
        if meta.is_file():
            try:
                data = json.loads(meta.read_text(encoding="utf-8"))
                available[(data["from_code"], data["to_code"])] = pkg
            except (OSError, ValueError, KeyError):
                pass

    staged = 0
    for pair in BUNDLE_PAIRS:
        pkg = available.get(pair)
        if pkg is None:
            raise SystemExit(
                f"Cannot bundle {pair[0]}->{pair[1]}: pack not installed. "
                f"Install it once with argostranslate, then rebuild."
            )
        dest = STAGE / f"{pair[0]}_{pair[1]}"
        shutil.copytree(pkg / "model", dest / "model")
        shutil.copy2(pkg / "sentencepiece.model", dest / "sentencepiece.model")
        shutil.copy2(pkg / "metadata.json", dest / "metadata.json")
        staged += folder_size(dest)
    print("staged %d translation packs (%.1f MB)" % (len(BUNDLE_PAIRS), staged / 1e6))
    return STAGE


SPEC_TEMPLATE = '''# -*- mode: python ; coding: utf-8 -*-
# Generated by build.py - edit that instead.
PRUNE_NAMES = {prune_names!r}
def is_pruned(path):
    norm = path.replace(chr(92), "/")
    return any(n in norm for n in PRUNE_NAMES) or norm.endswith(".pdb")

a = Analysis(
    ["translation.py"],
    pathex=[],
    binaries=[],
    datas={datas!r},
    hiddenimports={hidden!r},
    excludes={excludes!r},
    noarchive=False,
)

# PyInstaller's speech_recognition hook drags in a PocketSphinx model and
# FLAC binaries for other platforms. Nothing here can reach them.
a.datas = [entry for entry in a.datas if not is_pruned(entry[0])]
a.binaries = [entry for entry in a.binaries if not is_pruned(entry[0])]

pyz = PYZ(a.pure)
{body}
'''

ONEFILE_BODY = '''
exe = EXE(
    pyz, a.scripts, a.binaries, a.datas, [],
    name="LiveTranslator",
    debug=False, strip=False, upx=False,
    console=False, icon="translator.ico",
    runtime_tmpdir=None,
)
'''

ONEDIR_BODY = '''
exe = EXE(
    pyz, a.scripts, [],
    exclude_binaries=True,
    name="LiveTranslator",
    debug=False, strip=False, upx=False,
    console=False, icon="translator.ico",
)
coll = COLLECT(exe, a.binaries, a.datas, strip=False, upx=False,
               name="LiveTranslator")
'''

# Matches either path separator, so the spec needs no normalising
# Reachable only through recognisers this app never calls. Written with
# chr(92) so no backslash literal has to survive code generation.
PRUNE_NAMES = ("pocketsphinx-data/", "flac-linux", "flac-mac")


def is_pruned(path):
    norm = path.replace(chr(92), "/")
    return any(n in norm for n in PRUNE_NAMES) or norm.endswith(".pdb")


def write_spec(stage, onefile):
    datas = [(str(stage), "argos")]
    for pkg in ("faster_whisper", "ctranslate2", "onnxruntime", "sentencepiece"):
        from PyInstaller.utils.hooks import collect_data_files
        datas += collect_data_files(pkg)
    hidden = []
    for pkg in ("ctranslate2", "onnxruntime", "faster_whisper"):
        from PyInstaller.utils.hooks import collect_submodules
        hidden += collect_submodules(pkg)
    spec = SPEC_TEMPLATE.format(
        prune_names=PRUNE_NAMES, datas=datas, hidden=hidden, excludes=EXCLUDES,
        body=ONEFILE_BODY if onefile else ONEDIR_BODY,
    )
    path = ROOT / "LiveTranslator.spec"
    path.write_text(spec, encoding="utf-8")
    return path


def build(onefile=False):
    stage = stage_packs()
    if onefile:
        spec = write_spec(stage, onefile=True)
        subprocess.run([sys.executable, "-m", "PyInstaller", "--noconfirm",
                        str(spec)], cwd=ROOT, check=True)
        return
    cmd = [
        sys.executable, "-m", "PyInstaller", "--noconfirm", "--windowed",
        "--name", "LiveTranslator", "--icon", "translator.ico",
        "--collect-all", "faster_whisper",
        "--collect-all", "ctranslate2",
        "--collect-all", "onnxruntime",
        "--collect-data", "sentencepiece",
        "--add-data", f"{stage}{os.pathsep}argos",
    ]
    for mod in EXCLUDES:
        cmd += ["--exclude-module", mod]
    cmd.append("translation.py")
    subprocess.run(cmd, cwd=ROOT, check=True)


def prune():
    internal = DIST / "_internal"
    freed = 0
    for pattern in PRUNE_GLOBS:
        for path in sorted(internal.glob(pattern), reverse=True):
            if path.is_file():
                freed += path.stat().st_size
                path.unlink()
            elif path.is_dir():
                freed += folder_size(path)
                shutil.rmtree(path, ignore_errors=True)
    # tidy any directories the prune emptied
    for path in sorted(internal.rglob("*"), reverse=True):
        if path.is_dir() and not any(path.iterdir()):
            path.rmdir()
    return freed


def build_installer():
    """Wrap the folder build in a one-file installer.

    The installer is the thing to hand to someone: it unpacks once to
    %LOCALAPPDATA%, makes shortcuts, and fetches the speech model, so the
    app then launches at folder-build speed with nothing loose to delete.
    """
    if not (DIST / "LiveTranslator.exe").exists():
        raise SystemExit("Build the folder version first: python build.py")

    icon = ROOT / "translator.ico"
    shutil.copy2(icon, DIST / "translator.ico")   # so shortcuts get the icon

    cmd = [
        sys.executable, "-m", "PyInstaller", "--noconfirm", "--onefile",
        "--windowed", "--name", "LiveTranslatorSetup", "--icon", str(icon),
        "--add-data", f"{DIST}{os.pathsep}payload",
        "installer.py",
    ]
    subprocess.run(cmd, cwd=ROOT, check=True)
    setup = ROOT / "dist" / "LiveTranslatorSetup.exe"
    print()
    print("installer %8.1f MB   -> %s" % (setup.stat().st_size / 1e6, setup))
    print()
    print("Send this one file. It installs under LOCALAPPDATA/Programs,")
    print("adds Desktop and Start Menu shortcuts, and downloads the speech")
    print("model during setup so the first launch is already fast.")


if __name__ == "__main__":
    if "--installer" in sys.argv:
        build_installer()
        raise SystemExit(0)
    onefile = "--onefile" in sys.argv
    build(onefile=onefile)
    if onefile:
        single = ROOT / "dist" / "LiveTranslator.exe"
        print()
        print("single file %8.1f MB   -> %s" % (single.stat().st_size / 1e6, single))
        print()
        print("One file to copy. It unpacks to a temp folder on each launch,")
        print("so startup is slower than the folder build.")
        raise SystemExit(0)
    before = folder_size(DIST)
    freed = prune()
    after = folder_size(DIST)
    print()
    print("build   %8.1f MB" % (before / 1e6))
    print("pruned  %8.1f MB" % (freed / 1e6))
    print("final   %8.1f MB   -> %s" % (after / 1e6, DIST))
    print()
    print("Translation packs are bundled: the app translates offline on any")
    print("machine. The speech model (~145 MB) downloads once on first run.")
